/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-29 18:20:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tech.codehunt.pojo.ProjectPojo;
import java.util.ArrayList;
import tech.codehunt.dao.ProjectDaoImpl;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/messageprint.jsp", Long.valueOf(1706358253088L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("tech.codehunt.dao.ProjectDaoImpl");
    _jspx_imports_classes.add("tech.codehunt.pojo.ProjectPojo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Portfolio</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/unicons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- MAIN STYLE -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/tooplate-style.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("     .custom-btn-group {\r\n");
      out.write("     flex : wrap;\r\n");
      out.write("    display: flex; /* Use flexbox layout */\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("}\r\n");
      out.write(".small-text{\r\n");
      out.write("  padding:0px ;\r\n");
      out.write("}\r\n");
      out.write("     .animated-info{\r\n");
      out.write("     \r\n");
      out.write("     min-width: 290px;\r\n");
      out.write("     }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   ");

   String user = (String)session.getAttribute("login");
   
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- MENU -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-sm navbar-light\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.html\"><i class='uil uil-user'></i>Java Dev</a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("                aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav mx-auto\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"#about\" class=\"nav-link\"><span data-hover=\"About\">About</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"#project\" class=\"nav-link\"><span data-hover=\"Projects\">Projects</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"#resume\" class=\"nav-link\"><span data-hover=\"Resume\">Resume</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"#contact\" class=\"nav-link\"><span data-hover=\"Contact\">Contact</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");

                       if(user!=null){
                    	   
      out.write("\r\n");
      out.write("                    	   <li class=\"nav-item\">\r\n");
      out.write("                           <a href=\"admin.jsp\" class=\"nav-link\"><span data-hover=\"");
      out.print(user);
      out.write('"');
      out.write('>');
      out.print(user );
      out.write("</span></a>\r\n");
      out.write("                           </li> \r\n");
      out.write("                           ");
  
                       }
                       else{
                    	   
      out.write("\r\n");
      out.write("                    	   <li class=\"nav-item\">\r\n");
      out.write("                           <a href=\"admin.jsp\" class=\"nav-link\"><span data-hover=\"Admin\">Admin</span></a>\r\n");
      out.write("                       </li>\r\n");
      out.write("                       ");

                       }
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"navbar-nav ml-lg-auto\">\r\n");
      out.write("                    <div class=\"ml-lg-4\">\r\n");
      out.write("                      <div class=\"color-mode d-lg-flex justify-content-center align-items-center\">\r\n");
      out.write("                        <i class=\"color-mode-icon\"></i>\r\n");
      out.write("                        Color mode\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- ABOUT -->\r\n");
      out.write("    <section class=\"about full-screen d-lg-flex justify-content-center align-items-center\" id=\"about\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("      \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-7 col-md-12 col-12 d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"about-text\">\r\n");
      out.write("                        <small class=\"small-text\">Welcome to <span class=\"mobile-block\">my portfolio website!</span></small>\r\n");
      out.write("                        <h1 class=\"animated animated-text\">\r\n");
      out.write("                                <span class=\"mr-2\">Hey folks, I'm</span>\r\n");
      out.write("                                <div class=\"animated-info\">\r\n");
      out.write("                                    <span class=\"animated-item\">Haidar Ali</span>\r\n");
      out.write("                                    <span class=\"animated-item\">Java Developer</span>\r\n");
      out.write("                                    <span class=\"animated-item\">Tester</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </h1>\r\n");
      out.write("\r\n");
      out.write("                        <p>Building a successful product is a challenge. I am highly energetic in user experience design, interfaces and web development.</p>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"custom-btn-group mt-4\">\r\n");
      out.write("                         <!--  <a href=\"/myportfolio/Resume\" class=\"btn mr-lg-2 custom-btn\"><i class='uil uil-file-alt'></i> Download Resume</a>  -->\r\n");
      out.write("	                        <form action=\"Resume\" method=\"post\">\r\n");
      out.write("	                             <button class=\"btn mr-lg-2 custom-btn\">Download Resume</button>\r\n");
      out.write("	                        </form> \r\n");
      out.write("                          \r\n");
      out.write("                          <a href=\"#contact\" class=\"btn custom-btn custom-btn-bg custom-btn-link\">Get a free quote</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-5 col-md-12 col-12\">\r\n");
      out.write("                    <div class=\"about-image svg\">\r\n");
      out.write("                        <img src=\"images/undraw/undraw_software_engineer_lvl5.svg\" class=\"img-fluid\" alt=\"svg image\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- PROJECTS -->\r\n");
      out.write("    <section class=\"project py-5\" id=\"project\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-11 text-center mx-auto col-12\">\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("                        <h2>Things I have designed for digital media agencies</h2>\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"owl-carousel owl-theme\">\r\n");
      out.write("                     \r\n");
      out.write("                     ");

                        ArrayList<ProjectPojo>  alpp =  new ProjectDaoImpl().readProject();
                     
                        for(ProjectPojo p : alpp){
                     
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                          <div class=\"project-info\">\r\n");
      out.write("                            <img src=\"images/myproject/");
      out.print(p.getFilename() );
      out.write("\" class=\"img-fluid\" alt=\"project image\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        ");

                        }
                        
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- FEATURES -->\r\n");
      out.write("    <section class=\"resume py-5 d-lg-flex justify-content-center align-items-center\" id=\"resume\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6 col-12\">\r\n");
      out.write("                  <h2 class=\"mb-4\">Experiences</h2>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"timeline\">\r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                             <div class=\"timeline-yr\">\r\n");
      out.write("                                  <span>2019</span>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             <div class=\"timeline-info\">\r\n");
      out.write("                                  <h3><span>Project Manager</span><small>Best Studio</small></h3>\r\n");
      out.write("                                  <p>Proin ornare non purus ut rutrum. Nulla facilisi. Aliquam laoreet libero ac pharetra feugiat. Cras ac fermentum nunc, a faucibus nunc.</p>\r\n");
      out.write("                             </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                            <div class=\"timeline-yr\">\r\n");
      out.write("                                <span>2018</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-info\">\r\n");
      out.write("                                <h3><span>UX Designer</span><small>Digital Ace</small></h3>\r\n");
      out.write("                                <p>Fusce rutrum augue id orci rhoncus molestie. Nunc auctor dignissim lacus vel iaculis.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                            <div class=\"timeline-yr\">\r\n");
      out.write("                                <span>2016</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-info\">\r\n");
      out.write("                                <h3><span>UI Freelancer</h3>\r\n");
      out.write("                                <p>Sed fringilla vitae enim sit amet cursus. Sed cursus dictum tortor quis pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                            <div class=\"timeline-yr\">\r\n");
      out.write("                                <span>2014</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-info\">\r\n");
      out.write("                                <h3><span>Junior Designer<small>Crafted Co.</small></h3>\r\n");
      out.write("                                <p>Cras scelerisque scelerisque condimentum. Nullam at volutpat mi. Nunc auctor ipsum eget magna consequat viverra.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6 col-12\">\r\n");
      out.write("                  <h2 class=\"mb-4 mobile-mt-2\">Educations</h2>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"timeline\">\r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                             <div class=\"timeline-yr\">\r\n");
      out.write("                                  <span>2017</span>\r\n");
      out.write("                             </div>\r\n");
      out.write("                             <div class=\"timeline-info\">\r\n");
      out.write("                                  <h3><span>Mobile Web</span><small>Master Design</small></h3>\r\n");
      out.write("                                  <p>Please tell your friends about Tooplate website. That would be very helpful. We need your support.</p>\r\n");
      out.write("                             </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                            <div class=\"timeline-yr\">\r\n");
      out.write("                                <span>2015</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-info\">\r\n");
      out.write("                                <h3><span>User Interfaces</span><small>Creative Agency</small></h3>\r\n");
      out.write("                                <p><a rel=\"nofollow\" href=\"https://www.facebook.com/tooplate\">Tooplate</a> is a great website to download HTML templates without any login or email.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"timeline-wrapper\">\r\n");
      out.write("                            <div class=\"timeline-yr\">\r\n");
      out.write("                                <span>2013</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-info\">\r\n");
      out.write("                                <h3><span>Artwork Design</span><small>New Art School</small></h3>\r\n");
      out.write("                                <p>You can freely use Tooplate's templates for your business or personal sites. You cannot redistribute this template without a permission.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- CONTACT -->\r\n");
      out.write("    <section class=\"contact py-5\" id=\"contact\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-lg-5 mr-lg-5 col-12\">\r\n");
      out.write("            <div class=\"google-map w-100\">\r\n");
      out.write("              <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5201.665243032097!2d75.84084930224391!3d22.797543837168963!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3962fd0bbd8c1735%3A0x4010adec7b446fd1!2sAurobindo%20Hospital!5e0!3m2!1sen!2sin!4v1705856098331!5m2!1sen!2sin\" width=\"400\" height=\"300\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contact-info d-flex justify-content-between align-items-center py-4 px-lg-5\">\r\n");
      out.write("                <div class=\"contact-info-item\">\r\n");
      out.write("                  <h3 class=\"mb-3 text-white\">Say hello</h3>\r\n");
      out.write("                  <p class=\"footer-text mb-0\">010 020 0960</p>\r\n");
      out.write("                  <p><a href=\"mailto:hello@company.co\">hello@company.co</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"social-links\">\r\n");
      out.write("                     <li><a href=\"#\" class=\"uil uil-dribbble\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Dribbble\"></a></li>\r\n");
      out.write("                     <li><a href=\"https://www.instagram.com/ali01_haidar?igsh=cTNpeWx3MTdkYTRl\" class=\"uil uil-instagram\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Instagram\"></a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"uil uil-youtube\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Youtube\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-12\">\r\n");
      out.write("            <div class=\"contact-form\">\r\n");
      out.write("              <h2 class=\"mb-4\">Interested to work together? Let's talk</h2>\r\n");
      out.write("              ");

String message = (String)session.getAttribute("msg");
if(message != null)
{

      out.write("\r\n");
      out.write("<h4 style=\"text-align: center; color: red;\">");
      out.print(message);
      out.write("</h4>\r\n");
 
}
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("              <form action=\"Message\" method=\"post\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-6 col-12\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"name\" placeholder=\"Your Name\" id=\"name\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-lg-6 col-12\">\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Email\" id=\"email\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <textarea name=\"message\" rows=\"6\" class=\"form-control\" id=\"message\" placeholder=\"Message\"></textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"ml-lg-auto col-lg-5 col-12\">\r\n");
      out.write("                    <input type=\"submit\" class=\"form-control submit-btn\" id=\"myform\" value=\"Send Button\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <script>\r\n");
      out.write("    // Function to be called before form submission\r\n");
      out.write("    function onSubmitForm() {\r\n");
      out.write("        // Store the current scroll position in sessionStorage\r\n");
      out.write("        sessionStorage.setItem('scrollPosition', window.scrollY);\r\n");
      out.write("        return true; // Allow the form submission to proceed\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to be called after form submission\r\n");
      out.write("    window.onload = function () {\r\n");
      out.write("        // Retrieve the stored scroll position from sessionStorage\r\n");
      out.write("        var scrollPosition = sessionStorage.getItem('scrollPosition');\r\n");
      out.write("        // Set the scroll position if it exists\r\n");
      out.write("        if (scrollPosition !== null) {\r\n");
      out.write("            window.scrollTo(0, parseInt(scrollPosition));\r\n");
      out.write("            // Clear the stored scroll position to avoid interfering with future navigations\r\n");
      out.write("            sessionStorage.removeItem('scrollPosition');\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- FOOTER -->\r\n");
      out.write("     <footer class=\"footer py-5\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-12 col-12\">                                \r\n");
      out.write("                        <p class=\"copyright-text text-center\">Copyright &copy; 2019 Company Name . All rights reserved</p>\r\n");
      out.write("                        <p class=\"copyright-text text-center\">Designed by <a rel=\"nofollow\" href=\"https://www.facebook.com/tooplate\">Tooplate</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("               </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     </footer>\r\n");
      out.write("    <script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/Headroom.js\"></script>\r\n");
      out.write("    <script src=\"js/jQuery.headroom.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/smoothscroll.js\"></script>\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
